apiVersion: v1
kind: Secret
metadata:
  name: vaccine-order-secrets
stringData:
    KAFKA_USER: tls-user
    KAFKA_BOOTSTRAP_SERVERS: "eda-dev-kafka-bootstrap.eventstreams.svc:9093"
    QUARKUS_DATASOURCE_PASSWORD: adifficultpasswordtoguess
    QUARKUS_DATASOURCE_USERNAME: postgres
    KAFKA_CA_NAME: kafka-cluster-ca-cert
    QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres.vaccine.svc:5432/postgres
    # jdbc:postgresql://postgres.vaccine.svc:5432/postgres
    # QUARKUS_DATASOURCE_JDBC_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMudmFjY2luZS5zdmM6NTQzMi9wb3N0Z3Jlcwo=
    