apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-topics-cm
data:
  ORDER_TOPIC: "vaccine.public.orderevents"
  REEFER_TELEMETRY_TOPIC: "reefer.telemetries"
  SHIPMENT_PLAN_TOPIC: "vaccine.shipment.plans"
  INVENTORY_TOPIC:  "vaccine.inventory"
  TRANSPORTATION_TOPIC:  "vaccine.transportation"
  REEFER_TOPIC:  "vaccine.reefers"
  ALERS_TOPIC:  "vaccine.reeferalerts"
  