apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.shipment.plans
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 1
  replicas: 3

---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: reefer.telemetries
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 3
  replicas: 3

---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: test
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.inventory
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.transportation
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
---
apiVersion: eventstreams.ibm.com/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reefer
  namespace: eventstreams
  labels:
    strimzi.io/cluster: eda-dev
spec:
  partitions: 1
  replicas: 1
