
resources:
  - ./namespace.yaml
  - ./service-account.yaml
  - ./kafka/kafka-cluster.yaml
  - ./kafka/kafka-users.yaml
  - ./kafka/kafka-topics.yaml
  
configMapGenerator:
  - name: kafka-brokers
    literals:
      - KAFKA_BOOTSTRAP_SERVERS="vaccine-kafka-kafka-bootstrap:9093"
  - name: kafka-topics
    literals:
      - ORDER_TOPIC="vaccine.public.orderevents"
      - REEFER_TELEMETRY_TOPIC="reefer.telemetries"
      - SHIPMENT_PLAN_TOPIC="vaccine.shipment.plans"
      - INVENTORY_TOPIC= "vaccine.inventory"
      - TRANSPORTATION_TOPIC= "vaccine.transportation"
      - REEFER_TOPIC= "vaccine.reefer"
generatorOptions:
  disableNameSuffixHash: true

namespace: vaccine-solution