apiVersion: eventstreams.ibm.com/v1alpha1 
kind: KafkaConnector 
metadata: 
  name: pg-connector
  labels: 
    eventstreams.ibm.com/cluster: my-connect-cluster 
spec: 
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1 
  config: 
    database.dbname: orderdb
    database.hostname: postgres-db-postgresql.vaccine-solution.svc
    database.password: supersecret
    database.port: 5432
    database.server.name: orderdb
    database.user: postgres
    table.whitelist: public.orderevents
    plugin.name: pgoutput
    