apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: reefer.telemetries
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 1
  replicas: 1

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.reefer
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 1
  replicas: 1
