apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: vaccine.shipment.plans
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 1
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: reefer.telemetries
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 3
  replicas: 3

---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: test
  labels:
    strimzi.io/cluster: vaccine-kafka
spec:
  partitions: 1
  replicas: 1